"""add market structure, risk, volume liquidity, market context snapshot tables

Revision ID: 19dbdcbfedc4
Revises: 3eea2814d68b
Create Date: 2026-07-17 17:07:51.318151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dbdcbfedc4'
down_revision: Union[str, Sequence[str], None] = '3eea2814d68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_context_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('market_symbol', sa.String(length=15), nullable=True),
    sa.Column('sector_symbol', sa.String(length=15), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', 'calculation_version', name='uq_market_context_snapshot')
    )
    op.create_index(op.f('ix_market_context_snapshots_date'), 'market_context_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_market_context_snapshots_ticker_id'), 'market_context_snapshots', ['ticker_id'], unique=False)
    op.create_table('market_structure_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', 'calculation_version', name='uq_market_structure_snapshot')
    )
    op.create_index(op.f('ix_market_structure_snapshots_date'), 'market_structure_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_market_structure_snapshots_ticker_id'), 'market_structure_snapshots', ['ticker_id'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=15), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', 'calculation_version', name='uq_risk_snapshot')
    )
    op.create_index(op.f('ix_risk_snapshots_date'), 'risk_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_ticker_id'), 'risk_snapshots', ['ticker_id'], unique=False)
    op.create_table('volume_liquidity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', 'calculation_version', name='uq_volume_liquidity_snapshot')
    )
    op.create_index(op.f('ix_volume_liquidity_snapshots_date'), 'volume_liquidity_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_volume_liquidity_snapshots_ticker_id'), 'volume_liquidity_snapshots', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_liquidity_snapshots_ticker_id'), table_name='volume_liquidity_snapshots')
    op.drop_index(op.f('ix_volume_liquidity_snapshots_date'), table_name='volume_liquidity_snapshots')
    op.drop_table('volume_liquidity_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_ticker_id'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_date'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_market_structure_snapshots_ticker_id'), table_name='market_structure_snapshots')
    op.drop_index(op.f('ix_market_structure_snapshots_date'), table_name='market_structure_snapshots')
    op.drop_table('market_structure_snapshots')
    op.drop_index(op.f('ix_market_context_snapshots_ticker_id'), table_name='market_context_snapshots')
    op.drop_index(op.f('ix_market_context_snapshots_date'), table_name='market_context_snapshots')
    op.drop_table('market_context_snapshots')
    # ### end Alembic commands ###
