"""add scheduled_orders table

Revision ID: 3eea2814d68b
Revises: 6f173c4bb9be
Create Date: 2026-07-17 01:49:38.310562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eea2814d68b'
down_revision: Union[str, Sequence[str], None] = '6f173c4bb9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('order_json', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_orders_scheduled_at'), 'scheduled_orders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_orders_status'), 'scheduled_orders', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_orders_symbol'), 'scheduled_orders', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_orders_symbol'), table_name='scheduled_orders')
    op.drop_index(op.f('ix_scheduled_orders_status'), table_name='scheduled_orders')
    op.drop_index(op.f('ix_scheduled_orders_scheduled_at'), table_name='scheduled_orders')
    op.drop_table('scheduled_orders')
    # ### end Alembic commands ###
