"""initial schema

Revision ID: 6f173c4bb9be
Revises: 
Create Date: 2026-07-16 01:02:28.714586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f173c4bb9be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reinforcement_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('antecedent_tag', sa.String(length=100), nullable=False),
    sa.Column('behavior_tag', sa.String(length=100), nullable=False),
    sa.Column('consequence_tag', sa.String(length=100), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('follow_through_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', 'antecedent_tag', 'behavior_tag', 'consequence_tag', name='uq_reinforcement_stat')
    )
    op.create_index(op.f('ix_reinforcement_stats_antecedent_tag'), 'reinforcement_stats', ['antecedent_tag'], unique=False)
    op.create_index(op.f('ix_reinforcement_stats_behavior_tag'), 'reinforcement_stats', ['behavior_tag'], unique=False)
    op.create_index(op.f('ix_reinforcement_stats_scope_id'), 'reinforcement_stats', ['scope_id'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('behavioral_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('antecedent_tags', sa.JSON(), nullable=False),
    sa.Column('behavior_tag', sa.String(length=100), nullable=False),
    sa.Column('consequence_tag', sa.String(length=100), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('detection_rule_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_events_behavior_tag'), 'behavioral_events', ['behavior_tag'], unique=False)
    op.create_index(op.f('ix_behavioral_events_date'), 'behavioral_events', ['date'], unique=False)
    op.create_index(op.f('ix_behavioral_events_ticker_id'), 'behavioral_events', ['ticker_id'], unique=False)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('percentile_5y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', 'indicator_name', name='uq_indicator_snapshot')
    )
    op.create_index(op.f('ix_indicator_snapshots_date'), 'indicator_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_indicator_name'), 'indicator_snapshots', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_ticker_id'), 'indicator_snapshots', ['ticker_id'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_date'), 'news_events', ['date'], unique=False)
    op.create_index(op.f('ix_news_events_ticker_id'), 'news_events', ['ticker_id'], unique=False)
    op.create_table('options_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('max_pain', sa.Float(), nullable=True),
    sa.Column('expected_move', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_options_snapshot')
    )
    op.create_index(op.f('ix_options_snapshots_date'), 'options_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_options_snapshots_ticker_id'), 'options_snapshots', ['ticker_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_history_ticker_date')
    )
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    op.create_index(op.f('ix_price_history_ticker_id'), 'price_history', ['ticker_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bullish_pct', sa.Float(), nullable=False),
    sa.Column('neutral_pct', sa.Float(), nullable=False),
    sa.Column('bearish_pct', sa.Float(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_ticker_id'), 'reports', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_ticker_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_price_history_ticker_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_options_snapshots_ticker_id'), table_name='options_snapshots')
    op.drop_index(op.f('ix_options_snapshots_date'), table_name='options_snapshots')
    op.drop_table('options_snapshots')
    op.drop_index(op.f('ix_news_events_ticker_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_date'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_indicator_snapshots_ticker_id'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_indicator_name'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_date'), table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_index(op.f('ix_behavioral_events_ticker_id'), table_name='behavioral_events')
    op.drop_index(op.f('ix_behavioral_events_date'), table_name='behavioral_events')
    op.drop_index(op.f('ix_behavioral_events_behavior_tag'), table_name='behavioral_events')
    op.drop_table('behavioral_events')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_reinforcement_stats_scope_id'), table_name='reinforcement_stats')
    op.drop_index(op.f('ix_reinforcement_stats_behavior_tag'), table_name='reinforcement_stats')
    op.drop_index(op.f('ix_reinforcement_stats_antecedent_tag'), table_name='reinforcement_stats')
    op.drop_table('reinforcement_stats')
    # ### end Alembic commands ###
