/**
 * DEMO DATA — the Command Center dashboard summarizes outputs from the
 * analytical engine (market regime, confidence, catalyst scores,
 * probability-of-profit) and the Functional Behavioral Analysis engine.
 * Those engines are part of the build spec but aren't implemented yet, so
 * everything in this file is hand-authored, illustrative content.
 *
 * It is deliberately shaped like the real engine's output so that when the
 * backend lands, each export here can be swapped for a fetch/selector of the
 * same type with no change to the dashboard components. Anything sourced from
 * the connected broker (positions, account, live prices) is NOT in this file —
 * it stays real and is fetched in the components.
 */

import type { Rating } from "./types";

export type MarketRegime = "Bullish" | "Neutral" | "Bearish";
export type RiskLevel = "Low" | "Moderate" | "Elevated" | "High";
export type ImpactLevel = "High" | "Medium" | "Low";

/** Section 1 — hero summary. Generated by the analytical engine, not the LLM. */
export interface MarketSummary {
  regime: MarketRegime;
  regimeDetail: string;
  confidence: number; // 0-100
  risk: RiskLevel;
  highConvictionCount: number;
  majorCatalystCount: number;
  portfolioAlertCount: number;
  asOf: string;
}

export const marketSummary: MarketSummary = {
  regime: "Bullish",
  regimeDetail: "Moderately bullish · improving breadth",
  confidence: 82,
  risk: "Moderate",
  highConvictionCount: 7,
  majorCatalystCount: 4,
  portfolioAlertCount: 2,
  asOf: "Today, 9:31 AM ET",
};

/**
 * Section 2 — today's market brief. This is one of the few places an LLM may
 * be used, but it must be grounded only in model outputs, the economic
 * calendar, news summaries, technical data, and FBA outputs — never invented.
 */
export const marketBrief =
  "Markets remain moderately bullish following stronger-than-expected earnings and " +
  "improving market breadth. Treasury yields are rising slightly, creating pressure on " +
  "rate-sensitive sectors, while Technology continues to lead overall market performance. " +
  "Volatility stays contained in a calm regime, and defensive positioning is light — the " +
  "model reads today as constructive but not euphoric.";

/** Section 3 — highest-conviction opportunities. */
export interface ConvictionOpportunity {
  symbol: string;
  companyName: string;
  catalystScore: number; // 0-100
  recommendation: Rating;
  probabilityOfProfit: number; // 0-100
  expectedReturn: string;
  risk: RiskLevel;
  holdingPeriod: string;
  primaryCatalyst: string;
}

export const convictionOpportunities: ConvictionOpportunity[] = [
  {
    symbol: "NVDA",
    companyName: "NVIDIA Corp",
    catalystScore: 91,
    recommendation: "Buy",
    probabilityOfProfit: 68,
    expectedReturn: "+4.2%",
    risk: "Elevated",
    holdingPeriod: "2-10 days",
    primaryCatalyst: "AI capex commentary + 3 analyst upgrades",
  },
  {
    symbol: "UNH",
    companyName: "UnitedHealth Group",
    catalystScore: 84,
    recommendation: "Buy",
    probabilityOfProfit: 63,
    expectedReturn: "+2.9%",
    risk: "Moderate",
    holdingPeriod: "1-5 days",
    primaryCatalyst: "Healthcare sector leadership rotation",
  },
  {
    symbol: "AVGO",
    companyName: "Broadcom Inc",
    catalystScore: 79,
    recommendation: "Buy",
    probabilityOfProfit: 61,
    expectedReturn: "+3.5%",
    risk: "Moderate",
    holdingPeriod: "3-10 days",
    primaryCatalyst: "Semiconductor breadth expanding beyond NVDA",
  },
  {
    symbol: "JPM",
    companyName: "JPMorgan Chase",
    catalystScore: 74,
    recommendation: "Buy",
    probabilityOfProfit: 59,
    expectedReturn: "+2.1%",
    risk: "Low",
    holdingPeriod: "5-15 days",
    primaryCatalyst: "Financials firm as yields grind higher",
  },
  {
    symbol: "COST",
    companyName: "Costco Wholesale",
    catalystScore: 71,
    recommendation: "Hold",
    probabilityOfProfit: 55,
    expectedReturn: "+1.8%",
    risk: "Low",
    holdingPeriod: "5-15 days",
    primaryCatalyst: "Defensive quality bid, monthly sales due",
  },
];

/** Section 4 — market snapshot. Most-important markets only. */
export interface SnapshotRow {
  symbol: string;
  label: string;
  level: string;
  changePct: number;
}

export const marketSnapshot: SnapshotRow[] = [
  { symbol: "SPX", label: "S&P 500", level: "5,842.31", changePct: -0.4 },
  { symbol: "IXIC", label: "Nasdaq", level: "18,203.44", changePct: -0.7 },
  { symbol: "DJI", label: "Dow Jones", level: "42,118.05", changePct: -0.1 },
  { symbol: "RUT", label: "Russell 2000", level: "2,198.77", changePct: -1.1 },
  { symbol: "VIX", label: "VIX", level: "16.82", changePct: 6.3 },
  { symbol: "DXY", label: "US Dollar Index", level: "104.12", changePct: 0.5 },
  { symbol: "US10Y", label: "10-Yr Treasury", level: "4.31%", changePct: 2.4 },
  { symbol: "WTI", label: "Oil (WTI)", level: "$78.42", changePct: -0.9 },
  { symbol: "GOLD", label: "Gold", level: "$2,614.20", changePct: 0.3 },
  { symbol: "BTC", label: "Bitcoin", level: "$67,410", changePct: 1.6 },
];

/** Section 5 — today's market catalysts. */
export interface CatalystEvent {
  time: string;
  category: string;
  title: string;
  impact: ImpactLevel;
  assetsAffected: string;
}

export const todaysCatalysts: CatalystEvent[] = [
  {
    time: "8:30 AM ET",
    category: "Economic release",
    title: "CPI inflation print (consensus: cooling)",
    impact: "High",
    assetsAffected: "Rates, growth/tech, USD",
  },
  {
    time: "2:00 PM ET",
    category: "Federal Reserve",
    title: "FOMC minutes — data-dependent path in focus",
    impact: "High",
    assetsAffected: "Treasuries, financials, broad equities",
  },
  {
    time: "After close",
    category: "Earnings",
    title: "Mega-cap tech earnings season begins",
    impact: "High",
    assetsAffected: "Technology, communication services",
  },
  {
    time: "Ongoing",
    category: "Geopolitical",
    title: "Reports of escalating regional tensions",
    impact: "Medium",
    assetsAffected: "Oil, gold, defense, risk sentiment",
  },
];

/** Section 6 — portfolio alerts (used only when the user holds positions). */
export type AlertSeverity = "critical" | "warning" | "info";

export interface PortfolioAlert {
  severity: AlertSeverity;
  symbol?: string;
  title: string;
  detail: string;
}

/**
 * Educational guidance shown when the user has no open positions. Not an
 * alert stream — a "here's how to start" panel per the spec.
 */
export const gettingStartedGuidance: { title: string; detail: string }[] = [
  {
    title: "Start from today's market read",
    detail:
      "The regime and confidence up top tell you whether to lean aggressive or cautious before you pick a single name.",
  },
  {
    title: "Review a high-conviction opportunity",
    detail:
      "Open one of the ideas above to see the full catalyst, probability, and invalidation before committing capital.",
  },
  {
    title: "Place a small paper trade",
    detail:
      "Positions you open through the connected broker appear here with real, personalized risk alerts.",
  },
];

/** Section 7 — watchlist. */
export interface DashboardWatchRow {
  symbol: string;
  companyName: string;
  price: string;
  changePct: number;
  catalystScore: number;
  recommendation: Rating;
  probabilityOfProfit: number;
  hasNews: boolean;
}

export const dashboardWatchlist: DashboardWatchRow[] = [
  { symbol: "NVDA", companyName: "NVIDIA Corp", price: "$138.42", changePct: 1.2, catalystScore: 91, recommendation: "Buy", probabilityOfProfit: 68, hasNews: true },
  { symbol: "SNOW", companyName: "Snowflake Inc", price: "$158.90", changePct: -0.6, catalystScore: 48, recommendation: "Hold", probabilityOfProfit: 51, hasNews: true },
  { symbol: "PLTR", companyName: "Palantir Technologies", price: "$36.10", changePct: -2.1, catalystScore: 33, recommendation: "Sell", probabilityOfProfit: 42, hasNews: false },
  { symbol: "AAPL", companyName: "Apple Inc", price: "$228.14", changePct: 0.4, catalystScore: 62, recommendation: "Hold", probabilityOfProfit: 54, hasNews: false },
  { symbol: "AMD", companyName: "Advanced Micro Devices", price: "$164.72", changePct: 2.3, catalystScore: 77, recommendation: "Buy", probabilityOfProfit: 60, hasNews: true },
];

/** Section 8 — recent activity. */
export type ActivityKind = "trade" | "viewed" | "analysis" | "journal";

export interface ActivityItem {
  kind: ActivityKind;
  symbol: string;
  label: string;
  timeAgo: string;
}

export const recentActivity: ActivityItem[] = [
  { kind: "trade", symbol: "AVGO", label: "Bought 15 shares", timeAgo: "2h ago" },
  { kind: "analysis", symbol: "NVDA", label: "Reviewed analysis", timeAgo: "3h ago" },
  { kind: "journal", symbol: "UNH", label: "Logged a closed swing trade", timeAgo: "Yesterday" },
  { kind: "viewed", symbol: "JPM", label: "Viewed research", timeAgo: "Yesterday" },
];
